name: CI unit tests

on:
  push:
    paths:
      - '**.js'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Get the public IP of the runner
        id: get-ip
        shell: bash
        run: |
          echo "ip-address=$(curl https://checkip.amazonaws.com)" >> "$GITHUB_OUTPUT"

      - name: Permit the runner to access MongoDB Atlas
        id: allow-ip
        shell: bash
        run: |
          curl \
            --data '[{"ipAddress": "${{ steps.get-ip.outputs.ip-address }}", "comment": "GitHub Actions Runner"}]' \
            --digest \
            --header 'Accept: application/vnd.atlas.2023-02-01+json' \
            --header 'Content-Type: application/json' \
            --user "$USERNAME:$PASSWORD" \
            "https://cloud.mongodb.com/api/atlas/v2/groups/$GROUP_ID/accessList"
        env:
          GROUP_ID: ${{ secrets.ATLAS_GROUP_ID }}
          PASSWORD: ${{ secrets.ATLAS_PRIVATE_KEY }}
          USERNAME: ${{ secrets.ATLAS_PUBLIC_KEY }}
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Revoke the runner's access to MongoDB Atlas
        if: always() && steps.allow-ip.outcome == 'success'
        shell: bash
        run: |
          curl \
            --digest \
            --header 'Accept: application/vnd.atlas.2023-02-01+json' \
            --request 'DELETE' \
            --user "$USERNAME:$PASSWORD" \
            "https://cloud.mongodb.com/api/atlas/v2/groups/$GROUP_ID/accessList/${{ steps.get-ip.outputs.ip-address }}"
        env:
          GROUP_ID: ${{ secrets.ATLAS_GROUP_ID }}
          PASSWORD: ${{ secrets.ATLAS_PRIVATE_KEY }}
          USERNAME: ${{ secrets.ATLAS_PUBLIC_KEY }}
